LabMVCDB/Models/ErrorViewModel.cs
using System;

namespace LabMVCDB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LabMVCDB/Models/PersonaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Laboratorio3.Models
{
    public class PersonaModel
    {
        public string Nombre { get; set; }
        public int id { get; set; }
        public double Peso { get; set; }
        public double Estatura { get; set; }

        public PersonaModel()
        {
            this.Nombre = "Sin nombre";
            this.id = 0;
            this.Peso = 0.0;
            this.Estatura = 0.0;
        }

        public PersonaModel(int id, string Nombre, double Peso, double Estatura)
        {
            this.Nombre = Nombre;
            this.id = id;
            this.Peso = Peso;
            this.Estatura = Estatura;
        }

    }
}

LabMVCDB/Controllers/CalculadoraIMCController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laboratorio3.Models;

namespace Laboratorio3.Controllers
{
    public class CalculadoraIMCController : Controller
    {
        private PersonaModel[] personas;
        public ActionResult ResultadoIMC()
        {
            PersonaModel persona = new PersonaModel(1, "Cristiano Ronaldo", 84.0, 1.87);
            double IMC = persona.Peso / (persona.Estatura * persona.Estatura);
            ViewBag.IMC = IMC;
            ViewBag.persona = persona;
            return View();
        }
        public ActionResult ResultadosAleatoriosIMC()
        {
            Random random = new Random();
            personas = new PersonaModel[20];
            double[] IMCs = new double[20];
            for (int p = 0; p < 20; p++)
            {
                double peso = random.NextDouble() * (150 - 20) + 20;
                double estatura = random.NextDouble() * (2 - 1) + 1;
                PersonaModel persona = new PersonaModel(p, "Sin Nombre", peso, estatura);
                personas[p] = persona;
                IMCs[p] = personas[p].Peso / (personas[p].Estatura * personas[p].Estatura);
            }
            ViewBag.personas = personas;
            ViewBag.IMCs = IMCs;
            return View();
        }
    }
}

LabMVCDB/Controllers/HomeController.cs
using LabMVCDB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LabMVCDB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LabMVCDB/Views/CalculadoraIMC/ResultadoIMC.cshtml
@{ 
    ViewBag.Title = "IMC";
}
<!DOCTYPE  html>
<html>
    <head>
        <title> Resultado IMC </title>
        <meta charset="utf-8"/>
        <!--Esto es un comentario-->
        <!--en el head se coloca informacion que es para el navegador, script, css...-->
    </head>
    <body>
        <!--aqui inicia el cuerpo de la pagina que se esta creando (la vista)-->
        <h1> Resultado </h1>
        <div class="seccion_1" id="s1">
            <table class="table-bordered">
                <tr>
                    <th>Encabezado 1</th>
                    <th>Encabezado 2</th>
                    <th>Encabezado 3</th>
                </tr>
                <tr>
                    <td>@ViewBag.persona.Nombre</td>
                    <td>Fila 1, Columna 2</td>
                    <td>Fila 1, Columna 3</td>
                </tr>
                <tr>
                    <td>Fila 2, Columna 1</td>
                    <td>Fila 2, Columna 2</td>
                    <td>Fila 2, Columna 3</td>
                </tr>
            </table>
            <hr/>
        </div>
        <div class="seccion_2" id="s2">
            <ul>
                <li>Elemento 1</li>
                <li>Elemento 2</li>
                <li>Elemento 3</li>
            </ul>
            <hr/>
        </div>
        <div class="seccion_3" id="s3">
            <input type="button" value="Soy un Boton" /><hr/>
            <a class="btn btn-info"> Soy un link que parece boton </a>
        </div>
        <div class="seccion_4">
            @if (ViewBag.IMC > 20)
            {
                <div class="text-success">
                    <p>Mensaje</p>
                </div>
            }
            else
            {
                <div class="text-danger">
                    <p>Otro mensajke</p>
                </div>
            }
        </div>
    </body>
</html>

LabMVCDB/Views/CalculadoraIMC/ResultadosAleatoriosIMC.cshtml
<!DOCTYPE html>
<html>
<head>
    <title> Resultado IMC Aleatorio </title>
    <meta charset="utf-8" />
    <!--Esto es un comentario-->
    <!--en el head se coloca informacion que es para el navegador, script, css...-->
</head>
<body>
    <!--aqui inicia el cuerpo de la pagina que se esta creando (la vista)-->
    <h1> Resultados </h1>
    <div class="seccion_2" id="s2">
        <ul>
            <li>IMC menor que 18.5 -> peso insuficiente</li>
            <li>IMC 18,5 y 24,9 -> peso normal</li>
            <li>IMC mayor que 25 -> sobrepeso</li>
        </ul>
        <br>
    </div>
    <div class="seccion_3" id="s3">
        <a class="btn btn-info" asp-area="" asp-controller="Home" asp-action="Index">Regresar al inicio</a>
    </div>

    <hr />
    <div class="seccion_1" id="s1">
        <table class="table">
            <tr>
                <th>id</th>
                <th>Nombre</th>
                <th>Peso</th>
                <th>Estatura</th>
                <th>IMC</th>
            </tr>

            @for (var i = 0; i < @ViewBag.personas.Length; i++)
            {
        <tr>
            <td>@ViewBag.personas[i].id</td>
            <td>@ViewBag.personas[i].Nombre</td>
            <td>@ViewBag.personas[i].Peso</td>
            <td>@ViewBag.personas[i].Estatura</td>
            @if (@ViewBag.IMCs[i] > 18.5 && @ViewBag.IMCs[i] < 24.9)
            {
                <td style="color:green;">@ViewBag.IMCs[i]</td>
            }
            else
            {
                <td style="color:red;">@ViewBag.IMCs[i]</td>
            }
        </tr>

            }
            </table>
        <hr />
    </div>

</body>
</html>

LabMVCDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Karen and Fabiola page</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LabMVCDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabMVCDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabMVCDB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalculadoraIMC" asp-action="ResultadoIMC">IMC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalculadoraIMC" asp-action="ResultadosAleatoriosIMC">IMC Aleatorio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LabMVCDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>